// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DoxaFlameAPILib.Models;

public partial class Sermon
{
    public int SermonId { get; set; }

    public int SpeakerId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string ScriptureReference { get; set; }

    public string VideoUrl { get; set; }

    public string AudioUrl { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual ICollection<Service> Services { get; set; } = new List<Service>();

    public virtual Speaker Speaker { get; set; }
}