// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DoxaFlameAPILib.Models;

public partial class Service
{
    public int ServiceId { get; set; }

    public int ChurchId { get; set; }

    public DateTime ServiceDate { get; set; }

    public int? MemoryPassageId { get; set; }

    public int? SermonId { get; set; }

    public DateTime CreatedDate { get; set; }

    public virtual Church Church { get; set; }

    public virtual MemoryPassage MemoryPassage { get; set; }

    public virtual ICollection<Playlist> Playlists { get; set; } = new List<Playlist>();

    public virtual Sermon Sermon { get; set; }
}